In [1]:
import numpy as np

Dot multiplication functions.

$vector * vector$

In [6]:
u = np.array([2, 4, 5, 13])
v = np.array([3, 1, 4, 0])

In [9]:
u.shape, v.shape

((4,), (4,))

In [4]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [7]:
vector_vector_multiplication(u, v)

30

In [8]:
u.dot(v)

30

$vector * matrix$

In [10]:
# matrix
U = np.array(
    [[1, 1, 1, 1],
    [3, 4, 5, 7]]
)

In [14]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows, dtype=int)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [15]:
matrix_vector_multiplication(U, v)

array([ 8, 33])

In [13]:
U.dot(v)

array([ 8, 33])

$matrix * matrix$

In [17]:
# number of rows in V should be the same as number of columns in U
V = np.array([
    [2, 2, 2],
    [0, 0, 0],
    [1, 2, 3],
    [15, 16, 45]
])

In [16]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols), dtype=int)
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [18]:
matrix_matrix_multiplication(U, V)

array([[ 18,  20,  50],
       [116, 128, 336]])

In [20]:
# throws an error
matrix_matrix_multiplication(V, U)

In [21]:
U.dot(V)

array([[ 18,  20,  50],
       [116, 128, 336]])

In [23]:
# throws an error
# shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)
V.dot(U)

#### Identity Matrix

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.eye(3) * [5, 6, 7]

array([[5., 0., 0.],
       [0., 6., 0.],
       [0., 0., 7.]])

In [4]:
np.eye(3).dot([5, 6, 7])

array([5., 6., 7.])

In [6]:
np.eye(3) * [[10, 20, 30],
                [11, 22, 33],
                [14, 15, 16]]

array([[10.,  0.,  0.],
       [ 0., 22.,  0.],
       [ 0.,  0., 16.]])

In [7]:
# dot multiplication of identity matrix with any matrix returns that matrix
np.eye(3).dot([[10, 20, 30],
                [11, 22, 33],
                [14, 15, 16]])

array([[10., 20., 30.],
       [11., 22., 33.],
       [14., 15., 16.]])

#### Inverse Matrix
- `matrix.dot(inverse_matrix) = identity_matrix`

In [10]:
# singular matrix, no inverse matrix for it
matrix = np.array([[10, 20, 30],
                [11, 22, 33],
                [14, 15, 16]])
# throws an error -> singular matrix
# np.linalg.inv(matrix)

In [17]:
def is_invertible(a):
    # if matrix is singular returns False, else True
    return a.shape[0] == a.shape[1] and np.linalg.matrix_rank(a) == a.shape[0]

In [29]:
matrix = np.array([[10, 25, 30],
                [11, 25, 33],
                [14, 15, 16]])
is_invertible(matrix)

True

In [32]:
matrix_inv = np.linalg.inv(matrix)
matrix_inv

array([[-1.46153846e-01,  7.69230769e-02,  1.15384615e-01],
       [ 4.40000000e-01, -4.00000000e-01,  6.21724894e-17],
       [-2.84615385e-01,  3.07692308e-01, -3.84615385e-02]])

In [34]:
matrix.dot(matrix_inv).round(0)

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [36]:
matrix_inv.dot(matrix).round(0)

array([[ 1., -0., -0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])