In [1]:
import numpy as np

Dot multiplication functions.

$vector * vector$

In [6]:
u = np.array([2, 4, 5, 13])
v = np.array([3, 1, 4, 0])

In [9]:
u.shape, v.shape

((4,), (4,))

In [4]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [7]:
vector_vector_multiplication(u, v)

30

In [8]:
u.dot(v)

30

$vector * matrix$

In [10]:
# matrix
U = np.array(
    [[1, 1, 1, 1],
    [3, 4, 5, 7]]
)

In [14]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows, dtype=int)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [15]:
matrix_vector_multiplication(U, v)

array([ 8, 33])

In [13]:
U.dot(v)

array([ 8, 33])

$matrix * matrix$

In [17]:
# number of rows in V should be the same as number of columns in U
V = np.array([
    [2, 2, 2],
    [0, 0, 0],
    [1, 2, 3],
    [15, 16, 45]
])

In [16]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols), dtype=int)
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [18]:
matrix_matrix_multiplication(U, V)

array([[ 18,  20,  50],
       [116, 128, 336]])

In [20]:
# throws an error
matrix_matrix_multiplication(V, U)

In [21]:
U.dot(V)

array([[ 18,  20,  50],
       [116, 128, 336]])

In [23]:
# throws an error
# shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)
V.dot(U)